// <auto-generated />
using System;
using FootballLeaguesSimulation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FootballLeaguesSimulation.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Competition");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            Logo = "https://e7.pngegg.com/pngimages/115/195/png-clipart-graphics-uefa-europa-league-logo-football-football-uefa-europa-league-logo.png",
                            Name = "UEFA CHAMPIONS LEAGUE",
                            SeasonId = 1,
                            StartAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompetitionId = 1,
                            Name = "Group A"
                        },
                        new
                        {
                            Id = 2,
                            CompetitionId = 1,
                            Name = "Group B"
                        },
                        new
                        {
                            Id = 3,
                            CompetitionId = 1,
                            Name = "Group C"
                        },
                        new
                        {
                            Id = 4,
                            CompetitionId = 1,
                            Name = "Group D"
                        },
                        new
                        {
                            Id = 5,
                            CompetitionId = 1,
                            Name = "Group E"
                        },
                        new
                        {
                            Id = 6,
                            CompetitionId = 1,
                            Name = "Group F"
                        },
                        new
                        {
                            Id = 7,
                            CompetitionId = 1,
                            Name = "Group G"
                        },
                        new
                        {
                            Id = 8,
                            CompetitionId = 1,
                            Name = "Group H"
                        });
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("League");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "EUFA"
                        });
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("GuestTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoundId")
                        .HasColumnType("int");

                    b.Property<int>("Score1")
                        .HasColumnType("int");

                    b.Property<int?>("Score1ET")
                        .HasColumnType("int");

                    b.Property<int?>("Score1P")
                        .HasColumnType("int");

                    b.Property<int>("Score2")
                        .HasColumnType("int");

                    b.Property<int?>("Score2ET")
                        .HasColumnType("int");

                    b.Property<int?>("Score2P")
                        .HasColumnType("int");

                    b.Property<int>("Winner")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("GroupId");

                    b.HasIndex("GuestTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("RoundId");

                    b.ToTable("Match");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 2,
                            HomeTeamId = 1,
                            PlayedAt = new DateTime(2017, 9, 12, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 2,
                            Winner = 2
                        },
                        new
                        {
                            Id = 2,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 4,
                            HomeTeamId = 3,
                            PlayedAt = new DateTime(2017, 9, 12, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 0,
                            Winner = 3
                        },
                        new
                        {
                            Id = 3,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 1,
                            HomeTeamId = 4,
                            PlayedAt = new DateTime(2017, 9, 27, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 5,
                            Score2 = 0,
                            Winner = 4
                        },
                        new
                        {
                            Id = 4,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 3,
                            HomeTeamId = 2,
                            PlayedAt = new DateTime(2017, 9, 27, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 4,
                            Winner = 3
                        },
                        new
                        {
                            Id = 5,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 4,
                            HomeTeamId = 2,
                            PlayedAt = new DateTime(2017, 10, 18, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 2,
                            Winner = 4
                        },
                        new
                        {
                            Id = 6,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 3,
                            HomeTeamId = 1,
                            PlayedAt = new DateTime(2017, 10, 18, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 1,
                            Winner = 3
                        },
                        new
                        {
                            Id = 7,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 2,
                            HomeTeamId = 4,
                            PlayedAt = new DateTime(2017, 10, 31, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 2,
                            Winner = 2
                        },
                        new
                        {
                            Id = 8,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 1,
                            HomeTeamId = 3,
                            PlayedAt = new DateTime(2017, 10, 31, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 0,
                            Winner = 3
                        },
                        new
                        {
                            Id = 9,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 1,
                            HomeTeamId = 2,
                            PlayedAt = new DateTime(2017, 11, 22, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 0,
                            Winner = 2
                        },
                        new
                        {
                            Id = 10,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 3,
                            HomeTeamId = 4,
                            PlayedAt = new DateTime(2017, 11, 22, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 0,
                            Winner = 4
                        },
                        new
                        {
                            Id = 11,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 4,
                            HomeTeamId = 1,
                            PlayedAt = new DateTime(2017, 12, 5, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 2,
                            Winner = 4
                        },
                        new
                        {
                            Id = 12,
                            CompetitionId = 1,
                            GroupId = 1,
                            GuestTeamId = 2,
                            HomeTeamId = 3,
                            PlayedAt = new DateTime(2017, 12, 5, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 1,
                            Winner = 3
                        },
                        new
                        {
                            Id = 13,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 5,
                            HomeTeamId = 7,
                            PlayedAt = new DateTime(2017, 9, 12, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 0,
                            Winner = 7
                        },
                        new
                        {
                            Id = 14,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 8,
                            HomeTeamId = 6,
                            PlayedAt = new DateTime(2017, 9, 12, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 5,
                            Winner = 8
                        },
                        new
                        {
                            Id = 15,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 7,
                            HomeTeamId = 8,
                            PlayedAt = new DateTime(2017, 9, 27, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 0,
                            Winner = 8
                        },
                        new
                        {
                            Id = 16,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 6,
                            HomeTeamId = 5,
                            PlayedAt = new DateTime(2017, 9, 27, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 3,
                            Winner = 6
                        },
                        new
                        {
                            Id = 17,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 8,
                            HomeTeamId = 5,
                            PlayedAt = new DateTime(2017, 10, 18, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 4,
                            Winner = 8
                        },
                        new
                        {
                            Id = 18,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 6,
                            HomeTeamId = 7,
                            PlayedAt = new DateTime(2017, 10, 18, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 0,
                            Winner = 7
                        },
                        new
                        {
                            Id = 19,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 5,
                            HomeTeamId = 8,
                            PlayedAt = new DateTime(2017, 10, 31, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 5,
                            Score2 = 0,
                            Winner = 8
                        },
                        new
                        {
                            Id = 20,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 7,
                            HomeTeamId = 6,
                            PlayedAt = new DateTime(2017, 10, 31, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 2,
                            Winner = 7
                        },
                        new
                        {
                            Id = 21,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 7,
                            HomeTeamId = 5,
                            PlayedAt = new DateTime(2017, 11, 22, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 2,
                            Winner = 7
                        },
                        new
                        {
                            Id = 22,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 6,
                            HomeTeamId = 8,
                            PlayedAt = new DateTime(2017, 11, 22, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 7,
                            Score2 = 1,
                            Winner = 8
                        },
                        new
                        {
                            Id = 23,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 8,
                            HomeTeamId = 7,
                            PlayedAt = new DateTime(2017, 12, 5, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 1,
                            Winner = 7
                        },
                        new
                        {
                            Id = 24,
                            CompetitionId = 1,
                            GroupId = 2,
                            GuestTeamId = 5,
                            HomeTeamId = 6,
                            PlayedAt = new DateTime(2017, 12, 5, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 1,
                            Winner = 5
                        },
                        new
                        {
                            Id = 25,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 9,
                            HomeTeamId = 10,
                            PlayedAt = new DateTime(2017, 9, 12, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 6,
                            Score2 = 0,
                            Winner = 10
                        },
                        new
                        {
                            Id = 26,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 11,
                            HomeTeamId = 12,
                            PlayedAt = new DateTime(2017, 9, 12, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 0,
                            Winner = 0
                        },
                        new
                        {
                            Id = 27,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 12,
                            HomeTeamId = 9,
                            PlayedAt = new DateTime(2017, 9, 27, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 2,
                            Winner = 12
                        },
                        new
                        {
                            Id = 28,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 10,
                            HomeTeamId = 11,
                            PlayedAt = new DateTime(2017, 9, 27, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 2,
                            Winner = 10
                        },
                        new
                        {
                            Id = 29,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 11,
                            HomeTeamId = 9,
                            PlayedAt = new DateTime(2017, 10, 18, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 0,
                            Winner = 0
                        },
                        new
                        {
                            Id = 30,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 12,
                            HomeTeamId = 10,
                            PlayedAt = new DateTime(2017, 10, 18, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 3,
                            Winner = 0
                        },
                        new
                        {
                            Id = 31,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 9,
                            HomeTeamId = 11,
                            PlayedAt = new DateTime(2017, 10, 31, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 32,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 10,
                            HomeTeamId = 12,
                            PlayedAt = new DateTime(2017, 10, 31, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 0,
                            Winner = 12
                        },
                        new
                        {
                            Id = 33,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 10,
                            HomeTeamId = 9,
                            PlayedAt = new DateTime(2017, 11, 22, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 4,
                            Winner = 10
                        },
                        new
                        {
                            Id = 34,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 12,
                            HomeTeamId = 11,
                            PlayedAt = new DateTime(2017, 11, 22, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 0,
                            Winner = 11
                        },
                        new
                        {
                            Id = 35,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 11,
                            HomeTeamId = 10,
                            PlayedAt = new DateTime(2017, 12, 5, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 36,
                            CompetitionId = 1,
                            GroupId = 3,
                            GuestTeamId = 9,
                            HomeTeamId = 12,
                            PlayedAt = new DateTime(2017, 12, 5, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 0,
                            Winner = 12
                        },
                        new
                        {
                            Id = 37,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 16,
                            HomeTeamId = 15,
                            PlayedAt = new DateTime(2017, 9, 12, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 0,
                            Winner = 15
                        },
                        new
                        {
                            Id = 38,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 13,
                            HomeTeamId = 14,
                            PlayedAt = new DateTime(2017, 9, 12, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 3,
                            Winner = 13
                        },
                        new
                        {
                            Id = 39,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 15,
                            HomeTeamId = 13,
                            PlayedAt = new DateTime(2017, 9, 27, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 1,
                            Winner = 15
                        },
                        new
                        {
                            Id = 40,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 14,
                            HomeTeamId = 16,
                            PlayedAt = new DateTime(2017, 9, 27, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 0,
                            Winner = 16
                        },
                        new
                        {
                            Id = 41,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 13,
                            HomeTeamId = 16,
                            PlayedAt = new DateTime(2017, 10, 18, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 1,
                            Winner = 16
                        },
                        new
                        {
                            Id = 42,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 14,
                            HomeTeamId = 15,
                            PlayedAt = new DateTime(2017, 10, 18, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 1,
                            Winner = 15
                        },
                        new
                        {
                            Id = 43,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 16,
                            HomeTeamId = 13,
                            PlayedAt = new DateTime(2017, 10, 31, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 44,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 15,
                            HomeTeamId = 14,
                            PlayedAt = new DateTime(2017, 10, 31, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 0,
                            Winner = 0
                        },
                        new
                        {
                            Id = 45,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 15,
                            HomeTeamId = 16,
                            PlayedAt = new DateTime(2017, 11, 22, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 0,
                            Winner = 0
                        },
                        new
                        {
                            Id = 46,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 14,
                            HomeTeamId = 13,
                            PlayedAt = new DateTime(2017, 11, 22, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 1,
                            Winner = 13
                        },
                        new
                        {
                            Id = 47,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 13,
                            HomeTeamId = 15,
                            PlayedAt = new DateTime(2017, 12, 5, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 0,
                            Winner = 15
                        },
                        new
                        {
                            Id = 48,
                            CompetitionId = 1,
                            GroupId = 4,
                            GuestTeamId = 16,
                            HomeTeamId = 14,
                            PlayedAt = new DateTime(2017, 12, 5, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 2,
                            Winner = 16
                        },
                        new
                        {
                            Id = 49,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 17,
                            HomeTeamId = 18,
                            PlayedAt = new DateTime(2017, 9, 13, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 50,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 20,
                            HomeTeamId = 19,
                            PlayedAt = new DateTime(2017, 9, 13, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 2,
                            Winner = 0
                        },
                        new
                        {
                            Id = 51,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 18,
                            HomeTeamId = 20,
                            PlayedAt = new DateTime(2017, 9, 26, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 0,
                            Winner = 20
                        },
                        new
                        {
                            Id = 52,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 19,
                            HomeTeamId = 17,
                            PlayedAt = new DateTime(2017, 9, 26, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 53,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 20,
                            HomeTeamId = 17,
                            PlayedAt = new DateTime(2017, 10, 17, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 5,
                            Score2 = 1,
                            Winner = 17
                        },
                        new
                        {
                            Id = 54,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 19,
                            HomeTeamId = 18,
                            PlayedAt = new DateTime(2017, 10, 17, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 7,
                            Winner = 19
                        },
                        new
                        {
                            Id = 55,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 17,
                            HomeTeamId = 20,
                            PlayedAt = new DateTime(2017, 11, 1, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 1,
                            Winner = 20
                        },
                        new
                        {
                            Id = 56,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 18,
                            HomeTeamId = 19,
                            PlayedAt = new DateTime(2017, 11, 1, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 0,
                            Winner = 19
                        },
                        new
                        {
                            Id = 57,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 18,
                            HomeTeamId = 17,
                            PlayedAt = new DateTime(2017, 11, 21, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 58,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 19,
                            HomeTeamId = 20,
                            PlayedAt = new DateTime(2017, 11, 21, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 3,
                            Winner = 0
                        },
                        new
                        {
                            Id = 59,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 20,
                            HomeTeamId = 18,
                            PlayedAt = new DateTime(2017, 12, 6, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 60,
                            CompetitionId = 1,
                            GroupId = 5,
                            GuestTeamId = 17,
                            HomeTeamId = 19,
                            PlayedAt = new DateTime(2017, 12, 6, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 7,
                            Score2 = 0,
                            Winner = 19
                        },
                        new
                        {
                            Id = 61,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 23,
                            HomeTeamId = 21,
                            PlayedAt = new DateTime(2017, 9, 13, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 4,
                            Winner = 23
                        },
                        new
                        {
                            Id = 62,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 24,
                            HomeTeamId = 22,
                            PlayedAt = new DateTime(2017, 9, 13, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 1,
                            Winner = 22
                        },
                        new
                        {
                            Id = 63,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 21,
                            HomeTeamId = 24,
                            PlayedAt = new DateTime(2017, 9, 26, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 1,
                            Winner = 24
                        },
                        new
                        {
                            Id = 64,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 22,
                            HomeTeamId = 23,
                            PlayedAt = new DateTime(2017, 9, 26, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 0,
                            Winner = 23
                        },
                        new
                        {
                            Id = 65,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 24,
                            HomeTeamId = 23,
                            PlayedAt = new DateTime(2017, 10, 17, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 1,
                            Winner = 23
                        },
                        new
                        {
                            Id = 66,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 22,
                            HomeTeamId = 21,
                            PlayedAt = new DateTime(2017, 10, 17, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 2,
                            Winner = 22
                        },
                        new
                        {
                            Id = 67,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 23,
                            HomeTeamId = 24,
                            PlayedAt = new DateTime(2017, 11, 1, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 4,
                            Winner = 23
                        },
                        new
                        {
                            Id = 68,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 21,
                            HomeTeamId = 22,
                            PlayedAt = new DateTime(2017, 11, 1, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 1,
                            Winner = 22
                        },
                        new
                        {
                            Id = 69,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 21,
                            HomeTeamId = 23,
                            PlayedAt = new DateTime(2017, 11, 21, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 0,
                            Winner = 23
                        },
                        new
                        {
                            Id = 70,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 22,
                            HomeTeamId = 24,
                            PlayedAt = new DateTime(2017, 11, 21, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 0,
                            Winner = 24
                        },
                        new
                        {
                            Id = 71,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 24,
                            HomeTeamId = 21,
                            PlayedAt = new DateTime(2017, 12, 6, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 1,
                            Winner = 21
                        },
                        new
                        {
                            Id = 72,
                            CompetitionId = 1,
                            GroupId = 6,
                            GuestTeamId = 23,
                            HomeTeamId = 22,
                            PlayedAt = new DateTime(2017, 12, 6, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 1,
                            Winner = 22
                        },
                        new
                        {
                            Id = 73,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 28,
                            HomeTeamId = 27,
                            PlayedAt = new DateTime(2017, 9, 13, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 74,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 26,
                            HomeTeamId = 25,
                            PlayedAt = new DateTime(2017, 9, 13, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 3,
                            Winner = 26
                        },
                        new
                        {
                            Id = 75,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 27,
                            HomeTeamId = 26,
                            PlayedAt = new DateTime(2017, 9, 26, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 2,
                            Score2 = 0,
                            Winner = 26
                        },
                        new
                        {
                            Id = 76,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 25,
                            HomeTeamId = 28,
                            PlayedAt = new DateTime(2017, 9, 26, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 3,
                            Winner = 25
                        },
                        new
                        {
                            Id = 77,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 26,
                            HomeTeamId = 28,
                            PlayedAt = new DateTime(2017, 10, 17, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 2,
                            Winner = 26
                        },
                        new
                        {
                            Id = 78,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 25,
                            HomeTeamId = 27,
                            PlayedAt = new DateTime(2017, 10, 17, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 2,
                            Winner = 27
                        },
                        new
                        {
                            Id = 79,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 28,
                            HomeTeamId = 26,
                            PlayedAt = new DateTime(2017, 11, 1, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 80,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 27,
                            HomeTeamId = 25,
                            PlayedAt = new DateTime(2017, 11, 1, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 1,
                            Winner = 25
                        },
                        new
                        {
                            Id = 81,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 25,
                            HomeTeamId = 26,
                            PlayedAt = new DateTime(2017, 11, 21, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 82,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 27,
                            HomeTeamId = 28,
                            PlayedAt = new DateTime(2017, 11, 21, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 4,
                            Winner = 27
                        },
                        new
                        {
                            Id = 83,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 26,
                            HomeTeamId = 27,
                            PlayedAt = new DateTime(2017, 12, 6, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 2,
                            Winner = 26
                        },
                        new
                        {
                            Id = 84,
                            CompetitionId = 1,
                            GroupId = 7,
                            GuestTeamId = 28,
                            HomeTeamId = 25,
                            PlayedAt = new DateTime(2017, 12, 6, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 5,
                            Score2 = 2,
                            Winner = 25
                        },
                        new
                        {
                            Id = 85,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 29,
                            HomeTeamId = 32,
                            PlayedAt = new DateTime(2017, 9, 13, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 0,
                            Winner = 32
                        },
                        new
                        {
                            Id = 86,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 30,
                            HomeTeamId = 31,
                            PlayedAt = new DateTime(2017, 9, 13, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 1,
                            Winner = 31
                        },
                        new
                        {
                            Id = 87,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 32,
                            HomeTeamId = 30,
                            PlayedAt = new DateTime(2017, 9, 26, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 3,
                            Winner = 32
                        },
                        new
                        {
                            Id = 88,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 31,
                            HomeTeamId = 29,
                            PlayedAt = new DateTime(2017, 9, 26, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 3,
                            Winner = 31
                        },
                        new
                        {
                            Id = 89,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 30,
                            HomeTeamId = 29,
                            PlayedAt = new DateTime(2017, 10, 17, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 90,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 31,
                            HomeTeamId = 32,
                            PlayedAt = new DateTime(2017, 10, 17, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 91,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 29,
                            HomeTeamId = 30,
                            PlayedAt = new DateTime(2017, 11, 1, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 1,
                            Winner = 0
                        },
                        new
                        {
                            Id = 92,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 32,
                            HomeTeamId = 31,
                            PlayedAt = new DateTime(2017, 11, 1, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 1,
                            Winner = 31
                        },
                        new
                        {
                            Id = 93,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 32,
                            HomeTeamId = 29,
                            PlayedAt = new DateTime(2017, 11, 21, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 0,
                            Score2 = 6,
                            Winner = 32
                        },
                        new
                        {
                            Id = 94,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 31,
                            HomeTeamId = 30,
                            PlayedAt = new DateTime(2017, 11, 21, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 1,
                            Score2 = 2,
                            Winner = 31
                        },
                        new
                        {
                            Id = 95,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 30,
                            HomeTeamId = 32,
                            PlayedAt = new DateTime(2017, 12, 6, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 2,
                            Winner = 32
                        },
                        new
                        {
                            Id = 96,
                            CompetitionId = 1,
                            GroupId = 8,
                            GuestTeamId = 29,
                            HomeTeamId = 31,
                            PlayedAt = new DateTime(2017, 12, 6, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            RoundId = 1,
                            Score1 = 3,
                            Score2 = 0,
                            Winner = 31
                        });
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Round");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompetitionId = 1,
                            Name = "Groups"
                        },
                        new
                        {
                            Id = 2,
                            CompetitionId = 1,
                            Name = "Round of 16"
                        },
                        new
                        {
                            Id = 3,
                            CompetitionId = 1,
                            Name = "Round of 8"
                        },
                        new
                        {
                            Id = 4,
                            CompetitionId = 1,
                            Name = "Round of 4"
                        },
                        new
                        {
                            Id = 5,
                            CompetitionId = 1,
                            Name = "Final"
                        });
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Season");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "2017/2018"
                        });
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("GroupId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 1,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Benfica.png",
                            Name = "Benfica"
                        },
                        new
                        {
                            Id = 2,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 1,
                            Logo = "https://kassiesa.net/uefa/clubs/images/CSKA-Moscow.png",
                            Name = "CSKA Moskva"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MUN",
                            CompetitionId = 1,
                            GroupId = 1,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Manchester-United.png",
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = 4,
                            Code = "BAS",
                            CompetitionId = 1,
                            GroupId = 1,
                            Logo = "https://kassiesa.net/uefa/clubs/images/FC-Basel.png",
                            Name = "FC Basel 1893"
                        },
                        new
                        {
                            Id = 5,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 2,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Anderlecht.png",
                            Name = "Anderlecht"
                        },
                        new
                        {
                            Id = 6,
                            Code = "CEL",
                            CompetitionId = 1,
                            GroupId = 2,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Celtic.png",
                            Name = "Celtic"
                        },
                        new
                        {
                            Id = 7,
                            Code = "FCB",
                            CompetitionId = 1,
                            GroupId = 2,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Bayern-M%FCnchen.png",
                            Name = "FC Bayern München"
                        },
                        new
                        {
                            Id = 8,
                            Code = "PSG",
                            CompetitionId = 1,
                            GroupId = 2,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Paris-Saint-Germain.png",
                            Name = "Paris SG"
                        },
                        new
                        {
                            Id = 9,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 3,
                            Logo = "https://www.logofootball.net/wp-content/uploads/Qarabag-FK-Logo.png",
                            Name = "Qarabağ FK"
                        },
                        new
                        {
                            Id = 10,
                            Code = "CHE",
                            CompetitionId = 1,
                            GroupId = 3,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Chelsea.png",
                            Name = "Chelsea"
                        },
                        new
                        {
                            Id = 11,
                            Code = "ATL",
                            CompetitionId = 1,
                            GroupId = 3,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Atl%E9tico-Madrid.png",
                            Name = "Atlético Madrid"
                        },
                        new
                        {
                            Id = 12,
                            Code = "ROM",
                            CompetitionId = 1,
                            GroupId = 3,
                            Logo = "https://kassiesa.net/uefa/clubs/images/AS-Roma.png",
                            Name = "AS Roma"
                        },
                        new
                        {
                            Id = 13,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 4,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Sporting-CP-Lisbon.png",
                            Name = "Sporting Lisboa"
                        },
                        new
                        {
                            Id = 14,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 4,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Olympiakos-Piraeus.png",
                            Name = "Olympiakos Piräus"
                        },
                        new
                        {
                            Id = 15,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 4,
                            Logo = "https://kassiesa.net/uefa/clubs/images/FC-Barcelona.png",
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 16,
                            Code = "JUV",
                            CompetitionId = 1,
                            GroupId = 4,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Juventus.png",
                            Name = "Juventus"
                        },
                        new
                        {
                            Id = 17,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 5,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Spartak-Moscow.png",
                            Name = "Spartak Moskva"
                        },
                        new
                        {
                            Id = 18,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 5,
                            Logo = "https://kassiesa.net/uefa/clubs/images/NK-Maribor.png",
                            Name = "Maribor"
                        },
                        new
                        {
                            Id = 19,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 5,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Liverpool.png",
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 20,
                            Code = "SEV",
                            CompetitionId = 1,
                            GroupId = 5,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Sevilla.png",
                            Name = "Sevilla"
                        },
                        new
                        {
                            Id = 21,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 6,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Feyenoord.png",
                            Name = "Feyenoord"
                        },
                        new
                        {
                            Id = 22,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 6,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Shakhtar-Donetsk.png",
                            Name = "Shakhtar Donetsk"
                        },
                        new
                        {
                            Id = 23,
                            Code = "MCI",
                            CompetitionId = 1,
                            GroupId = 6,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Manchester-City.png",
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 24,
                            Code = "NAP",
                            CompetitionId = 1,
                            GroupId = 6,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Napoli.png",
                            Name = "Napoli"
                        },
                        new
                        {
                            Id = 25,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 7,
                            Logo = "https://kassiesa.net/uefa/clubs/images/FC-Porto.png",
                            Name = "Porto"
                        },
                        new
                        {
                            Id = 26,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 7,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Besiktas.png",
                            Name = "Beşiktaş JK"
                        },
                        new
                        {
                            Id = 27,
                            Code = "RBL",
                            CompetitionId = 1,
                            GroupId = 7,
                            Logo = "https://kassiesa.net/uefa/clubs/images/RB-Leipzig.png",
                            Name = "RB Leipzig"
                        },
                        new
                        {
                            Id = 28,
                            Code = "ASM",
                            CompetitionId = 1,
                            GroupId = 7,
                            Logo = "https://kassiesa.net/uefa/clubs/images/AS-Monaco.png",
                            Name = "AS Monaco"
                        },
                        new
                        {
                            Id = 29,
                            Code = "",
                            CompetitionId = 1,
                            GroupId = 8,
                            Logo = "https://kassiesa.net/uefa/clubs/images/APOEL-Nicosia.png",
                            Name = "APOEL"
                        },
                        new
                        {
                            Id = 30,
                            Code = "BVB",
                            CompetitionId = 1,
                            GroupId = 8,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Borussia-Dortmund.png",
                            Name = "Borussia Dortmund"
                        },
                        new
                        {
                            Id = 31,
                            Code = "TOT",
                            CompetitionId = 1,
                            GroupId = 8,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Tottenham-Hotspur.png",
                            Name = "Tottenham Hotspur"
                        },
                        new
                        {
                            Id = 32,
                            Code = "RMD",
                            CompetitionId = 1,
                            GroupId = 8,
                            Logo = "https://kassiesa.net/uefa/clubs/images/Real-Madrid.png",
                            Name = "R. Madrid"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Competition", b =>
                {
                    b.HasOne("FootballLeaguesSimulation.Models.League", "League")
                        .WithMany("Competitions")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballLeaguesSimulation.Models.Season", "Season")
                        .WithMany("Competitions")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Group", b =>
                {
                    b.HasOne("FootballLeaguesSimulation.Models.Competition", "Competition")
                        .WithMany("Groups")
                        .HasForeignKey("CompetitionId");

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Match", b =>
                {
                    b.HasOne("FootballLeaguesSimulation.Models.Competition", "Competition")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballLeaguesSimulation.Models.Group", "Group")
                        .WithMany("Matches")
                        .HasForeignKey("GroupId");

                    b.HasOne("FootballLeaguesSimulation.Models.Team", "GuestTeam")
                        .WithMany("GuestMatches")
                        .HasForeignKey("GuestTeamId");

                    b.HasOne("FootballLeaguesSimulation.Models.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId");

                    b.HasOne("FootballLeaguesSimulation.Models.Round", "Round")
                        .WithMany("Matches")
                        .HasForeignKey("RoundId");

                    b.Navigation("Competition");

                    b.Navigation("Group");

                    b.Navigation("GuestTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Round", b =>
                {
                    b.HasOne("FootballLeaguesSimulation.Models.Competition", "Competition")
                        .WithMany("Rounds")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Team", b =>
                {
                    b.HasOne("FootballLeaguesSimulation.Models.Competition", "Competition")
                        .WithMany("Teams")
                        .HasForeignKey("CompetitionId");

                    b.HasOne("FootballLeaguesSimulation.Models.Group", "Group")
                        .WithMany("Teams")
                        .HasForeignKey("GroupId");

                    b.Navigation("Competition");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Competition", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Matches");

                    b.Navigation("Rounds");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Group", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.League", b =>
                {
                    b.Navigation("Competitions");
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Round", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Season", b =>
                {
                    b.Navigation("Competitions");
                });

            modelBuilder.Entity("FootballLeaguesSimulation.Models.Team", b =>
                {
                    b.Navigation("GuestMatches");

                    b.Navigation("HomeMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
